feat(kre-go): krt-v2 golang runner support
konstellation-io/kre-runners pull request #123
Opened 2022-11-08 18:25 UTC by alexrodfe

## What

## Why

2022-11-10 16:45 UTC, JYisus requested changes

2022-11-10 16:45 UTC, JYisus commented on kre-go/runner.go
> +		success = false
This success var doesn't makes sense since it could be replace by constants.

2022-11-10 17:27 UTC, alexrodfe commented on .github/workflows/kre-go_tests.yaml
> +          go test -run TestHandlerContext_GetData -cover -v -coverprofile=coverage.out -covermode=atomic -coverpkg=./...
Now that you mention it, we could just run all tests. They were previously separated because not all were enabled. Now that they are, is a good chance yo change it. I'll change it.

2022-11-10 17:28 UTC, alexrodfe commented on kre-go/config/config.go
> +type Handlers struct {
Good catch :+1:

2022-11-10 17:29 UTC, alexrodfe commented on kre-go/context.go
> +func NewHandlerContext(cfg config.Config, nc *nats.Conn, mongoM mongodb.Manager,
Seems good to me

2022-11-11 11:10 UTC, alexrodfe commented on kre-go/context.go
> +// Once the entrypoint has been replied, all following replies to the entrypoint will be ignored.
I agree, I'll add some further explaining

2022-11-11 11:19 UTC, alexrodfe commented on kre-go/context.go
> +// SendOutput will send a any type of proto payload to the node's subject.
I see, I'll fix the typo and add further explanation

2022-11-11 11:21 UTC, alexrodfe commented on kre-go/context.go
> +// Use this function when you want to report a custom error in your workflow execution.
Having a second look at it, I think is best if we just delete the examples here and have them in the doc repo. So we only have explanation about functionality in code.

2022-11-11 11:44 UTC, alexrodfe commented on kre-go/main.go
> +// Responses must be sent through the handlerContext's sendOutput func.
I'll add an "if desired" to mark its optional

2022-11-11 11:44 UTC, alexrodfe commented on kre-go/main.go
> +		s, err := js.QueueSubscribe(subject, consumerName, runner.ProcessMessage,
Agreed

2022-11-11 11:47 UTC, alexrodfe commented on kre-go/runner.go
> +	handlerManager *Manager, handlerInit HandlerInit, mongoM *mongodb.MongoDB) *Runner {
Agreed

2022-11-11 11:48 UTC, alexrodfe commented on kre-go/runner.go
> +		end     time.Time
I've just refactored the ProcessMessage func, this has been done :ok_hand:

2022-11-11 11:50 UTC, alexrodfe commented on kre-go/runner.go
> +		success = false
Also deprecated in the refactor

2022-11-11 11:50 UTC, alexrodfe commented on kre-go/runner.go
> +	// Save the elapsed time for this node
I agree

2022-11-14 08:41 UTC, dfinteligenz commented on kre-go/main.go
> +// Responses, if desired, must be sent through the handlerContext's sendOutput func.
If I'm not mistaken, there are two ways of sending responses between nodes with `sendOutput` and `sendAny` functions.

```suggestion
// Responses, if desired, must be sent through the handlerContext's sendOutput or SendAny funcs.
```

2022-11-14 08:41 UTC, dfinteligenz commented on proto/kre_nats_msg.proto
> +enum MessageType {
As the value with index 0 is usually the default value for enums, it's common to define an `UNKNOWN` or `UNDEFINED` as the default value to avoid problems.

2022-11-14 08:48 UTC, alexrodfe commented on proto/kre_nats_msg.proto
> +enum MessageType {
I see, it's fine by me. I'll add an "undefined" default value.

2022-11-14 11:55 UTC, dfinteligenz approved these changes
Seems good to me :+1:

2022-11-14 19:05 UTC, JYisus approved these changes

2022-11-14 19:10 UTC, JYisus commented
@alexrodfe Great job!

2022-11-15 16:38 UTC, merged

2023-02-13 11:44 UTC, IGZEnriqueRomera commented
:tada: This PR is included in version 2.2.0 :tada:

The release is available on [GitHub release](https://github.com/konstellation-io/kre-runners/releases/tag/krt-files-downloader/v2.2.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-03-14 15:27 UTC, IGZEnriqueRomera commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/konstellation-io/kre-runners/releases/tag/kre-py-objstore/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-03-14 15:49 UTC, IGZEnriqueRomera commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/konstellation-io/kre-runners/releases/tag/kre-py-objstore/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: