feat(kre-go): Add key value stores
konstellation-io/kre-runners pull request #157
Opened 2023-03-10 12:50 UTC by kafkaphoenix

Implementation of key value storage for each scope (Node, Workflow, Project)

## Description
Add method Set, Get and Delete for key value storage. Set and Delete accept an optional scope if none is given it will use the default scope (Node), get will try to get the value from one scope is none is given starting by Node and going upwards

## Motivation and Context
A key value storage will let us to store configurations and share them.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other changes (ci configuration, documentation or any other kind of changes)

## Checklist:

- [ ] I have created tests for my code changes, and the tests are passing.
- [ ] I have executed the pre-commit hooks locally.
- [ x] My change requires a change to the documentation (create a new issue if the documentation has not been updated).
- [ ] I have updated the documentation accordingly.

2023-03-21 13:10 UTC, JYisus requested changes

2023-03-21 13:10 UTC, JYisus commented on kre-go/runner.go
> +		allScopes := []Scope{ScopeNode, ScopeWorkflow, ScopeProject}
```suggestion
		allScopes := [3]Scope{ScopeNode, ScopeWorkflow, ScopeProject}
```

2023-03-21 13:10 UTC, JYisus commented on kre-go/runner.go
> +
`if err != nil` clauses should be in the next line of the function that returned the error

2023-03-21 13:10 UTC, JYisus commented on kre-go/runner.go
> +		return fmt.Errorf("error deleting value with key %s from the key-value store: %w", key, err)
```suggestion
		return fmt.Errorf("error deleting value with key %q from the key-value store: %w", key, err)
```

2023-03-29 09:20 UTC, alexrodfe commented
Moved on to new branch so merge conflicts with object store would be easier to handle with. New PR regarding key value store is here:
https://github.com/konstellation-io/kre-runners/pull/174

2023-03-29 09:20 UTC, closed without merging