Nats kv store DRAFT
konstellation-io/kre-runners pull request #174
Opened 2023-03-27 15:52 UTC by alexrodfe

## Description

TODO
## Motivation and Context

TODO
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other changes (ci configuration, documentation or any other kind of changes)

## Checklist:

- [ ] I have created tests for my code changes, and the tests are passing.
- [ ] I have executed the pre-commit hooks locally.
- [ ] My change requires a change to the documentation (create a new issue if the documentation has not been updated).
- [ ] I have updated the documentation accordingly.

2023-04-03 07:39 UTC, dfinteligenz requested changes

2023-04-03 07:39 UTC, dfinteligenz commented on e2e/test_assets/exitpoint-vol/src/node/go.mod
@alexrodfe we are downgrading some dependency versions here, please check this out to see why.

2023-04-03 07:39 UTC, dfinteligenz commented on e2e/test_assets/exitpoint-vol/src/node/go.sum
Same here, we are downgrading some dependency versions

2023-04-03 07:39 UTC, dfinteligenz commented on e2e/test_assets/nodeC-vol/src/node/main.go
> +	if randomInt := rand.Intn(100); randomInt < 5 {
Why is this code block being executed randomly?

2023-04-03 07:39 UTC, dfinteligenz commented on e2e/test_go/go.mod
Dependency downgrade

2023-04-03 07:39 UTC, dfinteligenz commented on e2e/test_go/go.sum
Dependency downgrade

2023-04-03 07:39 UTC, dfinteligenz commented on go.work.sum
> +golang.org/x/sys v0.5.0/go.mod h1:oPkhp1MJrh7nUepCBck5+mAzfO9JrbApNNgaTdGDITg=
Dependency downgrade

2023-04-03 07:39 UTC, dfinteligenz commented on kre-go/context_configuration.go
> +	ScopeNode     Scope = "node"
Invert the names to make more sense.

```suggestion
	ProjectScope  Scope = "project"
	WorkflowScope Scope = "workflow"
	NodeScope     Scope = "node"
```

2023-04-03 07:39 UTC, dfinteligenz commented on kre-go/context_configuration.go
> +		return fmt.Errorf("could not find key value store given scope %q", scope)
```suggestion
		return fmt.Errorf("could not find a configuration for the given scope %q", scope)
```

2023-04-03 07:39 UTC, dfinteligenz commented on kre-go/context_configuration.go
> +		return fmt.Errorf("error storing value with key %q to the key-value store: %w", key, err)
```suggestion
		return fmt.Errorf("error storing value with key %q to the configuration: %w", key, err)
```

2023-04-03 07:39 UTC, dfinteligenz commented on kre-go/context_configuration.go
> +		return "", fmt.Errorf("error retrieving config with key %q, not found in any key-value store", key)
```suggestion
		return "", fmt.Errorf("error retrieving config with key %q, not found in any configuration scope", key)
```

2023-04-03 07:39 UTC, dfinteligenz commented on kre-go/context_configuration.go
> +		return "", fmt.Errorf("error retrieving config with key %q from the key-value store: %w", key, err)
```suggestion
		return "", fmt.Errorf("error retrieving config with key %q from the configuration: %w", key, err)
```

2023-04-03 07:39 UTC, dfinteligenz commented on kre-go/context_configuration.go
> +		return fmt.Errorf("could not find key value store given scope %q", scope)
```suggestion
		return fmt.Errorf("could not find the configuration for the given scope %q", scope)
```

2023-04-03 07:39 UTC, dfinteligenz commented on kre-go/context_configuration.go
> +		return fmt.Errorf("error deleting value with key %q from the key-value store: %w", key, err)
```suggestion
		return fmt.Errorf("error deleting value with key %q from the configuration: %w", key, err)
```

2023-04-03 07:39 UTC, dfinteligenz commented on kre-go/main.go
> +		logger.Errorf("Error connecting to key value stores: %s", err)
```suggestion
		logger.Errorf("Error connecting to configuration: %s", err)
```

2023-04-03 09:12 UTC, alexrodfe commented on kre-go/context_configuration.go
> +	ScopeNode     Scope = "node"
Fine by me :ok_hand:

2023-04-03 09:15 UTC, alexrodfe commented on e2e/test_assets/nodeC-vol/src/node/main.go
> +	if randomInt := rand.Intn(100); randomInt < 5 {
I'd like this node to execute some functions that test the object store and the key value store but I don't want this to be executed every time. So, to save up execution costs this will be done a few times per execution, so I came up with a quick solution about making it random. This can be debated as it is a quick solution to an opinionated testing.

2023-04-11 00:12 UTC, JYisus requested changes

2023-04-11 00:12 UTC, JYisus commented on kre-go/context_configuration_test.go
> +// SetupSuite will create a logger, setup a config, run a NATS mocked server,
IMO all these comments in test functions are superfluous, the code is clear enough.

2023-04-11 00:12 UTC, JYisus commented on kre-go/context_configuration_test.go
> +func (suite *ContextConfigurationTestSuite) TestSetProjectConfig() {
Adding multiple cases to the same test is not a good idea, each case should be split into different tests.

2023-04-11 00:12 UTC, JYisus commented on kre-go/main.go
> +	// Connect to MongoDB
Superluos comment

2023-04-11 00:12 UTC, JYisus commented on kre-go/main.go
> +	// Create context object store
Superluos comment

2023-04-11 00:12 UTC, JYisus commented on kre-go/main.go
> +	// Create context configuration
Superluos comment

2023-04-11 10:29 UTC, alexrodfe commented on kre-go/context_configuration_test.go
> +func (suite *ContextConfigurationTestSuite) TestSetProjectConfig() {
Noted, I have added multiple tests and upgraded the test suite.

2023-04-12 08:25 UTC, dfinteligenz approved these changes
Good job!

2023-04-12 08:27 UTC, merged

2023-04-12 08:30 UTC, IGZEnriqueRomera commented
:tada: This PR is included in version 3.1.0 :tada:

The release is available on [GitHub release](https://github.com/konstellation-io/kre-runners/releases/tag/kre-entrypoint/v3.1.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-04-12 10:03 UTC, IGZEnriqueRomera commented
:tada: This PR is included in version 3.3.0 :tada:

The release is available on [GitHub release](https://github.com/konstellation-io/kre-runners/releases/tag/kre-py/v3.3.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: